# Generated by Django 6.0.3 on 2026-03-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Влажность (%)')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Давление (мм рт. ст.)')),
                ('wind_direction', models.CharField(choices=[('N', 'Северный'), ('NNE', 'Северо-северо-восточный'), ('NE', 'Северо-восточный'), ('ENE', 'Восточно-северо-восточный'), ('E', 'Восточный'), ('ESE', 'Восточно-юго-восточный'), ('SE', 'Юго-восточный'), ('SSE', 'Юго-юго-восточный'), ('S', 'Южный'), ('SSW', 'Юго-юго-западный'), ('SW', 'Юго-западный'), ('WSW', 'Западно-юго-западный'), ('W', 'Западный'), ('WNW', 'Западно-северо-западный'), ('NW', 'Северо-западный'), ('NNW', 'Северо-северо-западный')], max_length=3, verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (м/с)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Данные погоды',
                'verbose_name_plural': 'Данные погоды',
            },
        ),
    ]
