# Generated by Django 6.0.3 on 2026-03-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='weather',
        ),
    ]
